script:
- curl -X POST $WEBHOOK_URL

env:
  global:
    secure: LV4byZNX5m/n/RexmZ7HNYfYUXjI80mPN/ybnYu8PtlyV7xsQin+iK3NphPTbva0j/HZFgMyrWFHoOn++eWaczsOb6lN/UCkU1Bdxry+efFlRMVE00GndDkKFAZylkSvEuObhwPaYCp4cFrsArPoVotGmkZpPI/zl4Xn8qVB7dh5Gimcw4rVVR59knPfzsvHEomc6ucXZPkozsBX1ATJGywFYWM+Wbd7GUY/my6heByWBFIoVW0sLjkRaldCu/P2807b4f/uZX1Af3ccJe7rRwYX/GH2FnTfJLXLB4yoNAfP78aQuWIEjmn3MWnJ7a6JbmlVRt+Y74HzaDiyZBZHN5MOlgfVpqlo6Jp8RPXdninkxdoVPBiCcw0CFT/H6Hu0D1QHs9zGS3+sa2j4YHdw7Dv01yeKmol18JeZJzRUd8CxXoPbIkMy5W8luk9u1OHnX8V8BLhyfR+Lsd9jiBfnKGRZT6W42lF6JXEJdND7ZrVsl66ChOWD1dHkNYPOkjCdr5VlecsiOqxHV5RQ6+RMu2Sf2vvhUwAIgvQFpEvJLx/l7k4biaGLYIxT8Cv+7AsuYO4yVlCpi35vSD4S62e7wtcZ2aO8cUULrU4sImsUYlI7MR2SkI60hB5MW0w2XwyyrMmJP3CFHBtvPwGq8hN8fRhgna+KjwyUuFLoZwapN4Q=
